# Generated by Django 3.1.1 on 2020-09-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ('produto',)},
        ),
    ]
